### PR TITLE
Improve UX

### LINKED ISSUE #23: Add the possibility to setup how to save first breaks in headers (byte, encoding, units)
Feature request described here

https://github.com/DaloroAT/first_breaks_picking/issues/21#issuecomment-1602099563

Right now `They are stored in the last 4 bytes (236 byte if counting from 0) to be decoded as an unsigned integer. Values are in microseconds.`

### LINKED ISSUE #24: Load and plot picks from file
Feature request described here

https://github.com/DaloroAT/first_breaks_picking/issues/21#issuecomment-1602103271

### LINKED ISSUE #25: Add different scaling options
Described here

https://github.com/DaloroAT/first_breaks_picking/issues/21#issuecomment-1602121125

### LINKED ISSUE #26: Show info about spatial positions for traces
Described here

https://github.com/DaloroAT/first_breaks_picking/issues/21#issuecomment-1602121125

### PR DESCRIPTION
**Pull request by DaloroAT**

### CODE REVIEW

**Comment by DaloroAT** [comment]
Hey @HHTC0

I published *beta* version with new functionality. Could you please try and check the new version?

```shell
pip install first-breaks-picking==0.3.0b0
```

**Comment by DaloroAT** [comment]
Changelist:

- Show info about spatial positions for traces
- Load and plot picks from file
- Add different scaling options
- Add the possibility to setup how to save first breaks in headers (byte, encoding, units)
- Add different visualization options

To install beta `pip install first-breaks-picking==0.3.0b0`

**Comment by HHTC0** [comment]
Hi @DaloroAT, I have tested it now. Apologies I could not respond you earlier due to some additional workload this and next week.

- Show info about spatial positions for traces - _worked however it did not displayed traces at correct position when plotting. It still kept the traces at regular spacing. Let's say I have receiver at 6, 8, and 12 with 10m missing. It should display the missing trace rather regular spacing between 6, 8 and 12m._
- Load and plot picks from file - _worked_
- Add different scaling options - _worked. If possible, if you can allow scale value input that allow entering value rather than scroll. E.g., 10 cm/sec or 20 cm/sec or in inches. Also, similar entry for trace density adjustment can be helpful._
- Add the possibility to setup how to save first breaks in headers (byte, encoding, units) - _worked_
- Add different visualization options - _worked_

Thanks again for your excellent work!

**Comment by DaloroAT** [comment]
@HHTC0 Glad to hear it worked out well!

---

> worked however it did not displayed traces at correct position when plotting. It still kept the traces at regular spacing. Let's say I have receiver at 6, 8, and 12 with 10m missing. It should display the missing trace rather regular spacing between 6, 8 and 12m.

I see, you want to put traces on some spatial grid, instead of plotting them sequentially with corresponding labels. In other words, the horizontal axis should be an axis in the mathematical sense, not just a place to put values.

---

> If possible, if you can allow scale value input that allow entering value rather than scroll. E.g., 10 cm/sec or 20 cm/sec or in inches. Also, similar entry for trace density adjustment can be helpful.

Scrolling by the mouse wheel allows you to zoom in and zoom out for X and T axes simultaneously. But you also can zoom/stretch/scale them separately. You need to press and hold the Right button, then move the mouse vertically to scale T or horizontally to scale X, or in both directions. A precise movement of the mouse diagonally will give an effect similar to scrolling with the mouse wheel. Is that what you want?

**Comment by DaloroAT** [comment]
@HHTC0 could you check mouse interaction?

**Comment by HHTC0** [comment]
@DaloroAT Just tested - works fine for panning, scaling and spacing adjustment. Well done!

**Comment by HHTC0** [comment]
@DaloroAT if you planning to develop it further. Having a BPF would be helpful for time picking.

**Comment by DaloroAT** [comment]
Bandpass filter? Yes, I can do it. Unfortunately, the development is taking a long time, since I can only work on the project on weekends.

Could you list common tools for time picking and tomography? It would be convenient to know ahead of time in order to better design the project.

**Comment by HHTC0** [comment]
@DaloroAT yes, bandpass is helpful when dealing with noisy data. Low pass is mainly required. No urgency.

Regarding time picking tools, can you please elaborate further?

**Comment by DaloroAT** [comment]
> Regarding time picking tools, can you please elaborate further?

Yes, but please be more specific

**Comment by HHTC0** [comment]
@DaloroAT the neural network is doing great job in initial picking. The manual time picking has already added ease of refining were required. Most of the borehole seismic time picking tool does allow picking on peak, trough, or inflection point tangent. 

Additionally, having the ability to reject a trace could be another useful functionality.

**Comment by DaloroAT** [comment]
> Most of the borehole seismic time picking tool does allow picking on peak, trough, or inflection point tangent.

Could you please share some examples of it? With videos, images, or at least with paint 😁 I don't know how it looks.

> having the ability to reject a trace could be another useful functionality.

You want to reject the exact list of traces, e.g. [1, 4, 5]. Or e.g. list of traces [1, 4, 5] with period T (or `Traces per gather`) to ignore [1, 4, 5, 1 + T, 4 + T, 5 + T, 1  + 2T, 4 + 2T, 5 + 2T] ? In a particular case, the list may consist of only one trace. I can implement both options.

I also already implemented the inversion of a list of traces, but this option is not in the desktop application right now.

**Pull request merged**
